package com.example.jetpackcomposedemo.components.models

data class Vessels(val title: String, val subtitle: String)

fun getVesselList(): List<Vessels> {
    val vesselList = mutableListOf<Vessels>()
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    vesselList.add(Vessels("MONTEPELLIER", "28 July  I  Tue"))
    return vesselList
}